# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e130283f4c632a8ab0fabfb0a0323e5862a16e5b3a9a91e8e143d7e7c70de8e008da8eba9119f38b2ed1da43d6de8d592a24e721cf34ece6b986baa2ce95cf

test:
  secret_key_base: abd6bdd14d1e21fd70e2259be8f319244793d361a04d7ec3b80ca783f86dee8fb6b0b4014c713722ca9c906378f6c1fd8813152ed278ea4afcdc76fd18031cad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e9cefbb15c2c27d725f6c920f89844785cc56cc568bf5e4ee13683cfbf3721e5f1ca042a26849ebd52dc1ea133bd169bd186220704fa8755d4621311ff209efd
